### ISSUE TITLE
Generating Relevant Data Files

### ISSUE THREAD

**Issue by JaiWillems** [JaiWillems/Celest#24]
I'm trying to run your program, but there're no julian.txt or gcrs.txt  file. What are these two files? How should I make it? Looking forward to your answer, thank you very much!

_Originally posted by @evanlee2021 in https://github.com/JaiWillems/celest/issues/23#issuecomment-1256278685_

**Comment by JaiWillems** [comment]
Hey Evan,

I am assuming you are referring to the `julian.txt` and `gcrs.txt` file names in the library's documentation. These files don't actually exist but were used to somewhat represent the data loading process.

The `julian.txt` file was to represent a source of times (in a Julian Day representation) that correspond to some satellite position data. The `gcrs.txt` file was used to represent a source of satellite positions in the Geocentric Celestial Reference System (GCRS).

You can get this data in two ways:
1. You can generate the data yourself using an orbit propagator and initial satellite position/velocity (I recommend the [Hypernova Library](https://pypi.org/project/hypernova-orbit/); this approach allows you to generate data specific for your satellite applications.
2. You can also import the data from one of Celest's test data sets such as `celest/tests/test_data/coordinate_validation_long.txt` on the `develop-v0.4.0` branch. Here the time column is `UTCModJulian` (which is in modified Julian, add `2430000` to convert to Julian time) and the position columns are `EarthMJ2000Eq.*`. You can see an example of loading this data in the `TestCoordinate` class' `setUp()` method located at `celest/tests/test_coordinates/test_coordinate.py` on the `develop-v0.4.0` branch.

I hope this helps!

**Comment by evanlee2021** [comment]
> Hey Evan,
> 
> I am assuming you are referring to the `julian.txt` and `gcrs.txt` file names in the library's documentation. These files don't actually exist but were used to somewhat represent the data loading process.
> 
> The `julian.txt` file was to represent a source of times (in a Julian Day representation) that correspond to some satellite position data. The `gcrs.txt` file was used to represent a source of satellite positions in the Geocentric Celestial Reference System (GCRS).
> 
> You can get this data in two ways:
> 
> 1. You can generate the data yourself using an orbit propagator and initial satellite position/velocity (I recommend the [Hypernova Library](https://pypi.org/project/hypernova-orbit/); this approach allows you to generate data specific for your satellite applications.
> 2. You can also import the data from one of Celest's test data sets such as `celest/tests/test_data/coordinate_validation_long.txt` on the `develop-v0.4.0` branch. Here the time column is `UTCModJulian` (which is in modified Julian, add `2430000` to convert to Julian time) and the position columns are `EarthMJ2000Eq.*`. You can see an example of loading this data in the `TestCoordinate` class' `setUp()` method located at `celest/tests/test_coordinates/test_coordinate.py` on the `develop-v0.4.0` branch.
> 
> I hope this helps!

Wow, I really appreciate that you could reply so timely. It's very helpful to me. Thank you!
